[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "cd django_backend && python manage.py migrate && gunicorn --bind 0.0.0.0:$PORT --pythonpath . wsgi:application"
